// CIS360/Week3/3.4/angular/helloworld/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  message: string = '';
  displayMessage: string = 'Hello World';

  updateMessage(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.message = input.value;
  }

  displayUserMessage(): void {
    this.displayMessage = this.message;
  }
}

<div class="app-container">
  <h1>Message Display App</h1>
  <div>
    <label for="messageInput">Message to Display:</label>
    <input
      id="messageInput"
      type="text"
      (input)="updateMessage($event)"
    />
    <button (click)="displayUserMessage()">Display Message</button>
  </div>
  <h2>{{ displayMessage }}</h2>
</div>

// CIS360/Week3/3.4/react/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  // State to store the user input
  const [message, setMessage] = useState('');
  // State to store the displayed message
  const [displayMessage, setDisplayMessage] = useState('Hello World');

  // Function to handle input change
  const handleInputChange = (event) => {
    setMessage(event.target.value);
  };

  // Function to handle button click
  const handleButtonClick = () => {
    setDisplayMessage(message);
  };

  return (
    <div className="App">
      <h1>Message Display App</h1>
      <div>
        <label htmlFor="messageInput">Message to Display:</label>
        <input
          id="messageInput"
          type="text"
          value={message}
          onChange={handleInputChange}
        />
        <button onClick={handleButtonClick}>Display Message</button>
      </div>
      <h2>{displayMessage}</h2>
    </div>
  );
}

export default App;
